---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-creds
  namespace: homepage-public
spec:
  encryptedData:
    password: AgC8j/AgJZA8WgHG+0wfn9KIn5RyZVklj93qRbHo+Du62FBCTUE78bR2Xikp92FUkELLwpQJrkYw8o3IHwItcp1xg3e74k/13fFf7fMl8Wf4BvdylMzvpTK7VFX8q9nMwvFGeCuxCffp/W5oqiLJQmtjelLIcxasHTxP1orPL4sq9J5ViLxPGKXBY6XtIK/AYM1/1XOn9MEbmFE0bkSe8vDRxSyakLg0kNvcKLL3q/+Q08yM0SgFNZrU6dPMl2tHGrQFzoQpBXkbDNHjmugNbW0bx2C5hN/3pacLYzdp66cDZ1fVKHBa79Pd9JTQT/DOER/QeSfOkmKyK4QlXZ3sphoFlfty6mjCtwwISsV572lLdqmrXxlHW7RPc9HGqurzX6GpmBg0tSIpvRpxVtWuuMKPd1ks4wTlqVkWzFAL8tNU9qIauBL0vMIknjQmVEHoRuOo8s8z8ZVp4+mCsP1zSoZhztWfpoCpsCGsXtJIo9yUawm+q87arHjuix2XaIFD7nJpI7DlmwHTlyl3Vj+80XGvQsC27SKLLvpCPxHXotTi6oWOd5Pn1Wg7BMN5KgQGFoSZVLLnaOwAmoov3fU6wUxZJtXbj5hF76WK1/QlJx/P6EUZKVsGV9T2wN8QjNl4hvAdOYUYHkQIqY/dO+yoWDOO3kVahkDSBLBdUgdrM7MGhUy2vJv/bD+CtxjS9mEF3vUsJkoO9khAaxRFwyt4u/dQRv1SJrwlV1Qk99V9CnSSXl/2HsI=
    username: AgBD/lJ1nHe1l+gB5CDr3GIYG63hOdn9ktGZS+3TtOftV4XWeA8+LT1vvUZmvUD7852+GJZauRdR6htev7+8+igjSNt19WGAa0Md+kQQN1NKwJHPyQb86Ah1PvnVWOj3+BCKC6+rYZwkdkE/m+R2ufAeAGFHQcEduhSzGC/Q6HADPjbRumgA3zBv+TXO9b3aOMRocszt5cS3MCTCsmGCWopE5Js/jBVf7+esozJ4Z+jOMjWTd+T+6PjaRNm+QNbi/dX3+lA4TTdYf/H0fKUWQFOTgRCk8Vs49/+csjm9q0FigZHSVcCy3X9U8yrc+lrwh65fd3xQK/qsylev8XWvjZY4HeGIEggU7xWgFEUG65U9j3GwEqjEMRL2XO6XI8IkZqCdSnYYd9Zd81laW635/ijlPZIz5mrjOqoyt2J+sbps9HrXEpkbkrO7xrDX5o2gPRu/dXwOuL7rDHSbsAm63uE/3q/GEcEf784+telT+ltgw3xQfw4UeOhUj13ieS6NzsZ+QUKwDvC/lTZsbWNrQAh99zGl/F6VLRP4JwpuVzcMOcFr1NjIM6a9Rt88wJcjDd1jjApnalZov1X45u6qvV453q4k6da0x4eg39gRevGDp/V3r6JIMY/Lbt7QFylmhb0Kp1DdN557Cf3mOVNusJP3TgtBW+TAdhBGXF3iNcD7AFCPW3cKK4ZUm+6iUDzkJxD/OmtfSZ9HvhYZarARx+Eo
  template:
    metadata:
      name: proxmox-creds
      namespace: homepage-public
    type: Opaque
