---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-creds
  namespace: homepage-public
spec:
  encryptedData:
    password: AgC8Tq4qXQvIuxBMQHB2dIXWpVwGxQRIs/h5zXDbKgm4HQGq328bsxr90qq+fiHoEHw/7HEjC8S+q7RZ5Lx/XG2cNgysnAoSOxmT0RNpcqyC75/zLHHTVlyw827aOzCVFAuon6zeu3LJ3W/3SRhc+g+Vl2tyjoBPnaJPoteLKikKVTbqB0Da5lJg3kDYCHf0GqrudCUAMZizghaXnZF2T3Q2jh/BwDm3Qb1ylleMZh2apwmeaA7WihvlyKXhK9/FPvsKhSD+Czzklhk/TlVS4LViZTlI5SNfLKWf+jtwpEbwkPp55eWAC2y+ikPq6xb4PYsyYRGM920qAhFNgNlCVKqplEHfKSxKto0eS71w535oNEaSt+zBTtbfI1cJb2RZh7YvfWhoO85tjiv2MWrGSLm2iJVBHg06qkI5dfQqnKv+48jIkUnykq3nhxBph6BASnQJR04Q0p1juZLAxAw4/JY599ILzCypdRSIM33sCloFIW8Y57XqQ9O3/7l+EhOO+etCCmI+BEJoIfgTtrRo/BxB8PiD7elMGdZAfokyphZoX71d4BGYGHctwDIl8/V8KU5A3CQS4NlGZ6KjUiH5PofyjrglOdpH5+MX2oVz+5KhUdVcI4Etrc6ZPkraj4YrI4bAZz7LIJJGz9wCj6MGoQY0mPjBMD5kPQgCzNZ1bNk1eL6qiclO9t+K/tTqIyl+r3MF8i/ftsmPm4qQgtHzaA==
    username: AgCU/iPbwwBGrgyjeDjq45GGXZyo6Sp1uAYO3MObhddbcG6GVwVjn+bqiKMibN0m++0dUeAbanDGGA/pJxEtpqiWK72/FQhs2ELrrlNIo/zh/CNoUQgPM/vbKTDL4ej5CoQztNBn1bioiHvRIrnspQ79h/JVeMXa3YjjL0Ow516xjKPYQnTJSMzt00VCXOTD2oeo+j8+sw2AaoqQdh5hREUpPldl2Dt0UlnH6/+heTpCQ38Kk6lzty6pEB1wWJpkA1aPIm3O43cM8GVEPwxZohcoyzo2VI7km94/ayMFdiEWuv7pTEP98w/l4RSyLt7E9Pq78nxyXRq83jMC24fzEAj6HVpFjlz+oPLb1IGuligvRMkfT80OxkQXDNUMbYdbnVrq+rfpkF5fr+ien+5mG94lMi9IrFb2AMDXoW/846MJhnuzV26wk611cRaXUjKjMTq+2JG6a86R0wMSm0y6YmG0VEIyXHkRyjj/4AQKvEND2TACfzJkStrlX1Ul5qxtlkmAnIhzkdwv/lcdBkzWhVjY5fNMVZdn+yu2EDrvpk9U/tcabEMPLNd86qtODSML7wCP1WvPEiPU+7DjtnucSZ66zjuEE9t0B9oPB8y5mNjqck7KSk6fvUuOcUZJCm5fvEZP7mhxXNXQW13W0BA/XAVY3nVE3mmwgDyzq/KsCGnNMGUrnZ8yIb0MeGiaVhXhP+LLvYI=
  template:
    metadata:
      name: unifi-creds
      namespace: homepage-public
    type: Opaque
