---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-creds
  namespace: homepage-public
spec:
  encryptedData:
    key: AgCRaDifI+7VurUm6hlAS3iCGy7AiXXxoKhNWdQzRP+979tCVHMcI6hCJfV90Bt3Rlx/Gp8eDOMnehCJ4MTCQX/H2C4iOO3Vb1L3Mqaweq240S2Abua46dk4HjAoYf7059SvwFM46jWidqE1qcLvx03nh9zfmiV/cYU2x0zXUbpZcfWJeg8YCTvfwfgMpAR+jgP+obsErM0I+09Ty2UgYpcBDb+f0m/wGHxjStmAYxyoi1Kzr8PsoKmB+tWOwvM2jfYJ8Pui7iHtTgDNE/O8VKtKQkfrmx0vTxojZt2rgCrL67jJvkEYcPH4In8Vb03hcbrRse58ztWhs440OlxxsKABvK+/4VxxonifRnn79fKYHyetKAZ1SNNmp2gOkYAV80KkMstJe54o6y538/+fqEk2uOLGU7EMfTwIsU7KMMEWPx0uqlyxSotUZLX0e3VGkl4E+9Xg2nxtsS1XhtwosHEmhigs2VJv9heF6cvAfWpYcABXhM9bNRr5BTznENm2NMuIQwSLfwBzv4QAXKa6zOVFlGj9i0Oy67Ry8EHPZYIFRSrwIsRVrbBuEby4CAsqe/WopmRqRQCpljpiw0lVD7awDdDCcVrRqFCaSvrdpSYzP43T6fiszqumoTx3pCSWinvCc9GdgHr6bZjX1Q5g5Kh597bHfk6pcNzWzl66xKlU615DJMlfbV4ttsVAPSmN3CMSrYijqbr8SGIX6fwVb4HNCpj6IzN7Cs5jCpeDtdljYeHfzKFPdYV8j0UTINrDOR0bSbH9DnRjC4yYvR6PWQoi5LXvd2tU/ilDF4/Iz1Am/752BZJCHRKTCtcqyAJS4OQ+Iyld4Y15nWwizCNsnAydIniz7yTzT29IQ3JTkDpZWSVSmG/UfS8R43J2DNpROQNwfze1IU+qXfoR9zapBFxxw6Gn2tAXPN3WYkPaV0fG8axDSYps+K7PDdaVB+oJ8MiNGBqqM/iRwuhzoeU6iUWuw/agQ288gCEEg+9CO8cjpI9PlePYR+cc7G5aS16ORPY=
  template:
    metadata:
      name: argocd-creds
      namespace: homepage-public
    type: Opaque
