---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-creds
  namespace: homepage-public
spec:
  encryptedData:
    key: AgAPXPYPBuzZQcDAv0KCblcxn5lPh3O/bJhE2xiUV99gZY5dON7imFBs9yqwk6LZ56Sr214GROLvYd17d63mdiQ1BgkAxOprnhhtr/zMbvJR3+e7X5VH5YhKPjgQvmy1nQa4AoikDjJ4enxiveuaUhGTAnMMkaahw8NZHkKBT2L9RqPWPT8qy5GzML7Szizl3wZ0J3TzFHVr8/ioV3f37+tbsV4CsKWddnY7cj49FC1KjKAl2XnbyDC+3Yojq3Okdxln5TMGNc+9aYk6QSuDak/FuZSgeYQjdu+s6zNjZT3bvGnazBd81/J/HwrCyow2fc1oQM5me28JwVzNg5Fc+QFw16kLoCLNEyr6pUs8YhcjdPhZ8Je6cWQouGOgt5SXgop3b6YGwMw/or72Z/t/LZoLaBn80VFnZ7wIufTjrfFwsX5eSDC6wIrwOj0FBoNezPHM2zjOW7eBSoaENK9yMTczUdqjrNxEYqP0XykEJ97xVZOrgQxNLuMgOABMi2E0K1o4qZXHzT8qQ/1jI0eqj/G34uf1x30kNeT/uliPzcxJA+G3zMhtU3QumI3FNy1vS601sMmNmukBpyRFmgXLL10YKGpfedUCHRRLQS2zD/1/QFr+yTICedC2y/tWg2NGMzE2wOQ6R0dwLopsxNir7EjZVay2JXl1T3N5A/4WwyRoxHtr3sfJp2v0SQ34TjVJxdO3pRIdfsCPomBJ0VguhbcXfCeLMX7vKXCGWr3dGtDO+zkQBAcRf2HjxrmFsJzT994DdI7aS1Mqg4sK7+97dstqlphGAbPKZaNDsotwoAeaDwJxx949PcS34uz49eE3w5o1LXveLIqHzOlzD/6j51h36ni2iOG+orLVqvtT4Bug4EsvkA292FwSSCb6qRWHbDwXVV70oNDjHrz18Yosy+8waSsQcKXCAIdjLUFdCoTO+8ATWzu7iy8=
  template:
    metadata:
      name: homeassistant-creds
      namespace: homepage-public
    type: Opaque
