---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-creds
  namespace: homepage-public
spec:
  encryptedData:
    password: AgAwJmvEKfo2EsQon+GFNzGXhor1FirbpDmshwnzOpHh8G5YKoX9VFwVRM8ganQ6GfuyyV0sEkgABLqOcrJZ5wthN6UOyXngINE09d+7alM4mZ0WXyiY60qmUPA8RZHPwwXZ6brTctAwCIejIBNw9k1sBb8/FOSTfp23UFM1NzZ0c7Iuf5hz8uQ9HBdd7TC4zSOwrlvkfEG8o7G/Th7EqvXer1JSbDLIvV4He6xmQnRuegzdjKmpdkqn0hX07u4xRfwTsblUwVHHDGfxvclrkVu/JamjbONqI+yJ7o55x0VK9dx25hdvMaHDBSe2q1kDoKCrmbDlHqMHXXwqg6gfGoEtjqKql5KD+0Rla0biR8G7xjsnidz33UxpMw4H9KhpaQFKNHekGT9dZZY/2cgz7ZNdqCN1jUZ6F/VmXOeGjO+/gqgGtQfbUxf4vhpqzdG90oS6Az9HSDYgxq8fadmQ/3Y5ug8s2s+H55dvfWq+ZSNim6hjTJ/8DHpH5lZxw6C69OVRlsIpc9rGZ0uXGPMHC6b4iQDSQLdHwCZDG2pItfpU5sPhzqufeGleBDSGv+0X7wgGI0C+PjlOQg5KfakFWCIt6/mbWDGfAVvZmb9pV658X9xFagHPA9vwB7iofLDUdBdekNBU/BHLvxZZ4Xsub6KGbS6ElnbcAnaUZQq/1AqjDRlCd9lH26rGl4q+W91j7bIvcIZxpkCUUEOlrVex4w==
    username: AgA9Qaah5JaOPKjFcPOWuadAZ4YICUld5LEv7kvs7vINAdCJeYTPK24WJI9CC9d8rcqik5vy+G7Ac7ZZZANLKekMj/4uYi1V0bNIxWUL8safw5pv+SXYoNcsJeWJXNXCLC8VmwH8eDit//F/j2OtAydGsyZyqAcS3Q72clkl8iU/aleLblVNLJzyVKfTjASqbszzys1fK8FMFo86oYYtMhyuAzBvvDylioILi46MMOcDBSiQDjUWpqMarxXYPTod0MlQu1OzEAJpJ17jyS+gxkLIyw1t+bceVao9J/qip54g1d9DqDjI0mnjxrLQrxUCBaPLnaM4EY4EOF585pKjqeN1cxuPVD72J9liNdcbtBkgH1wf5eRL+F/5fcmjddxTX/b0mWDeIUZyjE+0zUSkIDtCk2AI9XKrzLiM8J5oq5NJYZhzujbDQvHTqE5jObuGtEFm5p+efHeIRAoJpCucdlLyfXB8EadGEGUmYQfmhRjZXKTYrG9nK85S3FfAcvEFf52423JFPHcJbe8rBvNrwnsSwI7mKOz+i8VckSeQpwBCjQgepJD9PMHQQ15qERg+4NqCE4gSZp3reYv2Sakp7VaEv6i03kQ9HfblsK9cJJDR6Ee8fzNQDf1k7jQzrr9RRyO64M225diUmaXH35kumpRGX3R94ZiMHs9kiQimsS31DCZj1kfEth2FeHliEKyFeY8hICTj4w==
  template:
    metadata:
      name: grafana-creds
      namespace: homepage-public
    type: Opaque
