---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-creds
  namespace: homepage-public
spec:
  encryptedData:
    key: AgB+lRxx4xqoRxnUY0roEmeinev0GaUaUAzfoHIPMplRPmuuqlAQoUMK9PZIVrn6OK55oR0tWKo73Ajd1HZD6PCCW/IYTDxWqPOX/DLiayFeRxrwbrb9ZRsSoomMBk1lwgYmIjzGJ/UKDAYj0CdOwVhszCqHsXW0EVF8AngPsn38owxr2GZgSVHHnGyFOFr/cobytq6LlnaZHL3LZ3l/cGkzAHsqPx6PHul2EDVzJs1xMPhVEo9Jb+hXJgzarh6g/FsGr22yCMmyi4jvRWBTKGUMa8oW2k9z8hWGyiZ6rjfLfqq8rtMlwbGr6ttuyPe0KU30eSiYxS/fCOdBcNGdwweMmDB2OFu6gLpZbebqPFn1Jj6ocqE/4dx2WEsm0zck3epneL8quZgOaBKa0PfhZtPJJuselvkDRCtim8J4rlU/IxI9XnRpjVk/GSfPox93HoxNpzUkMe5ffUhAfL9DXEebwaSbL2GQET2fcdiY8MTiPzs2wJ7UnZkfur1RNLXDgw5DoOG/bxvvbD92u36AalOLrh4JNB8fNN5vJ0IAZv+Ha0rYUwAC5jx0Z8WG4pzKNgarssiYD8E0/7RNdONzYJZrRawJ7HrK77MrKAof43rzMFQQNkzGqlOzSxqc0Rz7L/oRBTKsyO5A0a6V3h6kaH9dHTAgd/Abh1XvL9vdLmLNa+4/TgHAT9nnb0aU1ZF0MRpU3LkcvHkDLES4RTKtMV1lREDHJBGBn+jDrjK7DqbG7OyW8AjpUGxZg8kgZJlIaYzzGFuI/t0MtOgsKK7pQ+ph9BZOpF5Qr5OmMS/KEM6NrGGgg7+MTPZ7wJlH6XQCL1D/FKCKLEnomLjX47fRUUZNAjVqsZBwYT6wteu+kePxxUndyhtDNLBnWvyD0qvCxtkAIij1xjQJgimmaqu3EDTGwxi+F5WIlWNzIt0wqy8yUWy1SHgi0MoNgc9cT+LtSdyJtJe+1fBHN8RV0xaHJAOE2uIx4LiD9BXNTBKxX5dBcx7FJmC1M3OF0dJE9HimXCI=
  template:
    metadata:
      name: argocd-creds
      namespace: homepage-public
    type: Opaque
