---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflare-tunnel-lusostreams
spec:
  encryptedData:
    token: AgAUO7T2rVqs0WL7zX1VjNjA+zklgS0zhyiQhX3l0ybNpDXGApJMlC2Q32z/paPsP9M0g0l4IVidVwnxWkb2HoKSt4fr2knmzJgxKTljzuQvR2RbACT0J9JskznsyHrfwS9bZ4jmKBDq7kYBcVWkCS+klJ3Z8YzTboj1wqZDSFYN/eBQ+m70dm8nzy0JWEiIcdmYHHrb/V0zZkCvrl/Y/ZehdVniH1oylwYAX4NTHxWH7GF2R6rb3NREEgXPaaVjFPiCbPVrPm1EUGXcEpP1wyh1T+7HTqEe0601JNA7yF4nkgOUBmiy1aKNSw6B8LrqIotKV0Y2r8g4PK3uy5cCkNwcMihZ+TeODyU60NUCfEp/WoBg0x1kyJaHM0XA67ZdOs9h4GoD554I/5IFJQRrxJmSKDYkWEvIo4CGS2gJUQIE1lLz4JlIv0nno7Xe9zrCHUxOWZ1jFnMpH45xxiNL7yeTTXnGGTTz6fdtCzAOVTsFCalczut+XfLbZFE8RJqFAvBfFHA8MOIVTWXbOW9uQLK6uazdoHB6ikGoZepDBQWiIGRIa21IdlsAXDVkk1AVhBpxvGVEp0MAPtUMwewz211CnSQ2meA8XMLBLnT8iigZHGzUdIOSKWe0QeOrvTNPwkooJusxzDJrywAUaW5k962zwnCdPNT0y7dGd4ev64bEO+QV/DJcTTRe+ZCp/kP21d7MkR6st2FXeKEnv2G66t+uPl0AQNX9pyqhAUnWRe8Bzc+X9m9DXhsfvUEtCIFsAgQQKSXJHi0s/T0W0VQBzNEFMqsMNcgKdFf7QKqV+oAvjuegKILWodYsAJ5MAObgHlgkoym3YnBPoUsyRag5QFP3Wa+XkRmnC9u8CVgOX+pIo07RLXs2Ty/d3YCIxqd8jaOM+BCwj+hqjGw+szapdrU6r9ftv09KLJHCN6s/5txE6g+09k7N+DWQ
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflare-tunnel-lusostreams
    type: Opaque
