apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare-tunnel-lusostreams
  labels:
    app: cloudflared-lusostreams
spec:
  selector:
    app: cloudflared-lusostreams
  ports:
  - name: metrics
    port: 2000
    targetPort: metrics
    protocol: TCP
