apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Lisbon"
        - name: HOMEPAGE_VAR_TITLE
          value: "Homelab Dashboard"
        - name: HOMEPAGE_VAR_SEARCH_PROVIDER
          value: "google"
        - name: LOG_TARGETS
          value: "stdout"
        - name: HOMEPAGE_CONFIG_FILE
          value: "/app/config/settings.yaml"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "10.10.10.208"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/config/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: homepage-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  type: LoadBalancer
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
