---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-creds
  namespace: homepage
spec:
  encryptedData:
    password: AgAgxSQiVCxgGl9eKmZ1f5lPV2K+Ni4DSGms0mLwUyBm1tmGSsy8aNCrQiO8aoox5QopWYEVnp5vs+ul1T5RcES8wjcBaD42LsHWNBwrNrS/reJeN6Fg0UhBrw36DtxAs+0M1zbuCsayJWYPTP0Jhy4NtaL53wcyH/znRdH2CDgAnQR8dG3dLMwPtoWIOthpQXRyUKsFNwBc/JzC1/oc+RSRmMgfOyB07e5B4tkN5LM7dzy3GFGc+DxXGiHbxveEVTTmCOr/uBGXnIK6Ik0jR7AKlqn42HkyESS//Mf0w5QEUFg/MZ2D6Ozftv8WRm/+SoACC2kHnUp08rFXSMcWPQ8EesMZSd8C3s+c0ozxmW4IphQtmlVWR0ERLP65YIyE3TeoMEFtiFRqFvKCerQlD5r4j4DVgV0sXt0Qweaoz/wpb9Buc5kNfPRjyURgAbYyJAO041N4TrZplZ/PyKyeOUDBCmbGB6eVn7pV8AROavFpl9GQ0IC+440PUxKCvV0J8yEu3mVM1T3yNUfFgptAZu8phLtRBqIg7kEDf6BsM4iGB66/B6oaoB27OdZ91nK5BxawKMgk/nob+uC1Do/dMcH8Vqj0gCmL0Qk4/4wJSiwTJO5kZCNAOOqmHOy/62UBQxZ+Ln6MBifct1QJT0/F1N7vdAgzIUcOPc78P7gBV/4EV108Yc79V3WNyS4BnWVbv8gASCe3I6B4g8z60I79N/YiSxG8DA4WsPaRIFfPAjOKioL6A8U=
    username: AgAKNx8JgDlis0Y4XsiNxZYwRkEk/r2TN0tj0i7EckK1p7cM7kXmVBmFnBycPaRUKZLhVNJKchULtGjqr/s5nPK11ipqp2qeRKZgTkD2ZiK89/MaJQHTsfLGfJjUGLBr/j860+PqwVTDOJXYNnb/qUQuLtuEbosz3XtLrt2mQBR1Ak8V7EOlspq7gGXgnCCeLtopI5JO9HLEX3MoDFWoMLFv8hR6OICH1yGp+0+GyMH7sibej7m/c8hndhl9kuwUr8HepMlFqAYPbvauIUuYp798E0svJu3a2d0tA9X0MZAyC9XA1y4wNgF51aYUxBQYkkd35TQGjakQ74LyIWMhSh8fJj6NImNxUDQK0AB19jy/cV00Ntf9GxUPAhYqyT420Pb9a8vHaufNoVAFHlGEp5UfNn33zeD0rhEv0FCIxLLZQNlfprgAWAvvIl19LPK7Zg9hZ3m+mYUBNqbHYPWQGudsusAPQ4kaG5/n+WC+pwSPBeJtyX4mqfXEbV+STOwxaIKTWGwt+Mj1vWPHdlDOy83TWeBVlz2+Zaf1GtjbfGSvzcCnI/3EX+41eCdE0YtP3jSgEcTV0U3Szw0rnOLXwAsbKM/p2ecspgBF+V3u0SJf655pZk0emKclLlGJpgj6pSj9uqGm2r2KAGDq3985y3C0Ce41Hgmu8FOVan7PYuInQjLl0YF7/+HjJ1dKKQa+0wns6Q4pfjFluM43X8ZhIA7G
  template:
    metadata:
      name: proxmox-creds
      namespace: homepage
