---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-creds
  namespace: homepage
spec:
  encryptedData:
    stdin: AgB+WFDfstWd7NPkkv2Lfs1LpBp7sDkobCnTbf71tmuFqahQAP2vvxAPtNwnr2MKd00UFtwhXq+TkC52dEyvRlaygdLNt/ykMfG+h1pbY2laIcQ5krr2QO/Wz3t9w+6hyZvUrHwlhklUD70pfThQpGBObaitBXHP6qU/xyCeI9xg5jFh40M6QNOqrFf4gd2R1oHSnHqsZvlo1hl0T2WYCYnW0kO1fe9Q5GmTQnbK5dpzBtGeExC29axVyEarO5m9dZLYkpsZbqDOwV1EBXbwkw95IvYxT7F+PzGSopUg1X5wDBMP2Ai24+kNNjsKMTesUgxEyJzUt3v+plYRI/vD6ktpjMzu6CKfiGUCIWvz6Nwd7gJxn3W6cp2gVgmnP4CFVc4ASEpKioBtxVO++ZmNkPTlS+im7LAae6mVoUszOuYMzGfpVAlAFjRpSlaOq+GFpdBKitH11x4pkzMRj8NI/U614NZOyEWqin+uphgUdNsdp9HcZaOlvZV1dVHfTfRjwWrJnNFhsjiOxjPbg2UyVufrR7NzZq7yNZwy4FBtKpd6wZg6MRHick1qeR5w/MQ24FnrymKevgYZX8pttoqtkjcf/jVJ5EsS6Mw+kmX9P0Ym7cuYwBqPkUcGbNRnZRkE7DaAkR9clA5XhZxYxKr4F5yPD+qPhN9ndITN3x5JVlAjAxZtablNdzLlvpsSYWZmzEWOysMVvpQImh/Az4oceEp8PLQniijmtBd/zmKtUWMu9thrwwphkpMzFO6ODyX1qCi773CTtR3RSr2wFfvQuvwDM4N/g3k75U0Jf2mLcQJQ2nC9C75CkbbaKzGRsUaS6EvLBoQxoS6z2sKdnmbuLDVX4tLAWdjWK4aygVGMy9rVZsWt8wzPCebru7rxLAmNdz0AxsfT37sym7qpeGuhwdPvUwrgoIwfyLKY8WiZy/b7RHzeXfmLML4plNwFV/hS8RZHqHHvhApuPfwuTboA9CJbFz5I+t+82q9jMLetoCxOmQRQ8j2og7qfERhcLf0RHujbKmx4pqbZBISXcNoCs59Bcy/J/tLztmWm4+T+Oexz45YpiEZI8kRLZqgKFUvavG3YXm+PkCoQdfhSxJF5uvTHxdl5FgKbhcPJsN7ugJS9tcI3my+VXAVupZJUqe3ufM55/2L49KuAYOTWI5ivBmFFRtbYM8EGjlxTqPQKgtKlkhqKfdB5DBupPmg6c5p5GsXprttYCUsyvjOapGA0B6npCXwVbg==
  template:
    metadata:
      name: unifi-creds
      namespace: homepage
