---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-creds
  namespace: homepage
spec:
  encryptedData:
    stdin: AgAu4UqyuBABoriYXVvjeNXfNV8TTI59o7KgacwWDNA0vkm/q20lGoQheSUtm91ogXfU+P1vGPOfOOQ9JCOGziewCJeOpxtKoMXw3yqqpcndgrC1PiPxR7yMsxEbpzbdJBJ0d2JwK/9XEG4tOtGpDn+6adirSJBj9N4gyMQzutGkPtCQQVuQREUVJucJKi+ETj9BgT2QfIF+IdAmjwdP4IWmVE4Ib7TsACKQ5rER5IX/fh58ltzYYMTrxplB8ERoD8804ikgY3ZnffaTWkF+McxEcqzgYiB4iVe3kO/27rFf7CRBXYm0wi77Qp8VkWOcc5vpUACDYmULigeoOXMJV0wkEhieUIjK8ig3eoTflJpUtWXXX1Rpg5pfkbCf6vgue/9ZOWj1LXDzeUcpjLYO36ThU08fPK9iXhYvfejPGQnrGANbdKb4qPm8ySAJRWaX8jDNSz55w9jONpGVaGvxAzdn/CXWYSuYOYtze7/qmxgkkHC7b+rJo7LhZq98h47QOZPyZMqT129BIeUwg5O/d7m1usOVoY4xGBKPar4IjZlzqJRBgacJ6/1Zx3cu/535joC+OpmYEmHG42fZi+h2Ezr4ZCvbXLE0tBiZQdu6B7v9gBHqhEu23YfFgYvhneWNehdJkIaX7KnJZsJp3+L7EBiuKaDKb92UMhVIZDLpts15TQKaOat0z1EX5hHxpK3xKuNh/D7tZb7cMO6z3EWGlRrEOdnFlLTRC4cSPN6CakRSZrMQse49eaQnoTJx//su+N2f+MzdT87BR2tzn/jLxJVHuLcRVgEeD2etjvbDoLU0dwKjKGoHVrBstsucfpFW1ERW6kTxpnc9T/lxMhFs2JR9kXbI7FRW9E/sne5ikoiTEJ68cVyniUvtbTPAGXukK53gz244tLemU+Ct7XzuhvgP+TMT2N3C7Vo/CunEzmxUvVQa5AUo4kRhoFtB8c+Q8x2A8B8XzXXCDoJFdfsu+Zhwd37/YIbm/oPxSmYT4fBGrBeaqrTQL1h4IXWttmepo+f9tm6urKI7MkeNF5EFpDgXEQdm8+NzM7FzPCE2p97ohWsz4J3WWfOFNiYzsVROg98YYiAS4Gz45B6XvohBf+GRwanm9W2PmWzgynn/m/8MDV5rl7+ljV0i2lcvkKKPcrzz55nOAZ7nK1ZSRAM3X+y9jWDb0K+uov63dm6eXpQo6sAPWzL8PWJsGpJTf70tj/IC+ZkV2ixb1F3p4ko95qzska4jjwHQlCp/EFLkwDJQNUSVZsYdenaCvQ==
  template:
    metadata:
      name: grafana-creds
      namespace: homepage
