---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-creds
  namespace: homepage
spec:
  encryptedData:
    password: AgBPh9LfTvXis4/Z+ZdSJaSi+LDMANW5LxAp5yfZBeC7N0DRgSGzMmTAlyhachkXBFVvdHCDYzLG/Zc+qcTZaSlz923i+MhENLdus9CtR+ngsQZy2JLlYw2sdR8M6LuDTLNNr3DOk04ibY8Wce+F7AqpObToCMWibHuLQNtguwNaER7OGBNI1ov6RU/uLSQ0r7DdeLBijINLf7k16/U1jhO0Ct4h0pyjH6u5tA09Cf/AHJOxpyEgBkUcpI95im6VLO6Bu8z05aDnRWSoQ924wdDHnUD60dgRHCf62YQefNHIGHY20gn8MGB0+kIkWbNBnzYXk4PWxe0kmXTqxcprAsonF1coK1CG6kJwO2lSy3nhlyvKLs0dDWQazs0wikIq42wNHMcb/ru7pPmwPBsAYhGm/xHqxv0qa9lKhPwHLMwooUJpxu/sJHmGaURUq+c+OLpqRgM4kSS5mHOXh8PyB5lh0WvoVj+5UgYTgrxXsQX0yPwOTMepeR0MSoDRSuIq73kHVuxr3rcz4lovlkyFNJhYwiDVeQ+hDqYHjn0ztv0CF2vP7olDrI7/imGyYa2qjP35QUVHMcfo8JegZmZT03EdgTrz423PXhxDbK6PnfaWocTbnJBEK3tbZsrGNDzHgMo2MnttH3+QEBsfhmV/uD/t6FsLyfCPzgumOnxGbF2MGz3osuxPWeVqLHrYD/FuvpHsbJITb8JLO4wWdda5hNO+
    username: AgBNrFeJdeBwexfZWvQWYxhn73hokvlCL+D1Pp8B5TaBdU10aGVDvNwZ5Tj8KFjcl4eliUd1C4u2FCnwaQ88jGImv5YAYjEZPfk1jayiiMESuiPCegc/xKU2DLfiPKxVsF1gtvRUKQo3qjHZzZma5gciXDQFHSc79yGsgJ8510u1LpdIpOXk6Hwb3OCUHu8Vhdz2w3LBY7rIfIUP/hrfC8gbA2NWwJBV99pog3XBuNMvGXhY1UqYjf6MHdoUA2mA/Mi+qwFgO++5h7+fH9Hlog5SCW/pL1DrVjR3tCB53Y79hMZYqP2Sfnc6CukolPpSFnVqZHOWMlhA/vTJRoYW+TPafE5G/5zCu0gYYa9C0IxuSkaR4xSCp3a1HQw+uexCb3tc+BtIPE+lBR5cUJchTau5/qbcUOJOrTMSfRnLovyzCtrexnQoUwaVRTaeMc37HUfJ33xWhfulhFM5vTk3t34R+CTaNQHKtAyEFyhsPemj/K8tWfz82AQh5YfCBbIxQjLqa7WX5paTtnVAwEPBY89LxS7rfLEqj+aRN97Me1R2z5MCX6YfVGSQargrnomJtjX6xH/6YGiHkOjyXVsM4tFRG7WmwuBVYYv4B4c3Gi+j6if8nPaKnv7lJwXTN/3Hx8/kE+Gxqf2MCrfdx9NKYMlxnLtjIYQgOB3UncPHUxLC2cUfcXI4vaicS6MmvzTMZgFbOBqclDLogQPypL3WYjY=
  template:
    metadata:
      name: proxmox-creds
      namespace: homepage
