---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-creds
  namespace: homepage
spec:
  encryptedData:
    key: AgBBSO683jsrRYe8XZ/cN3IPzGU9XSoFjW4yR7jHhgBXLuOMkUqiJoJkBcz0rO4g/ydUnME08Mz4diRFNdPASQrIjg12vnnOjWIj203Et9HkLh1s68/SVK6G5sGihI55i8C3+E+D90Y+WSA7pCA0t254Td5suME+eW9cneOljnNUnpG3mJ7V9c7m6YBC5Pmd2AaMXCGKwkD2woPwYY8YRak6y3yOmJAlVIvBOticq4UoqXRaDGcg2YgnObMQR9UKzyvRCiX4DLT65Hm4+adTts5+W1GZZrFy/SIj6wcmKAxiVQZKN7TmTua7so6njOiecmgBLxxUsr9oxMwY4RM5vz0CSfpG37R++Jm/L4Ex+BKyX8aUsQp6w6Iwr43LmLoM8kx37MjYymZW06NMxLzmIqJ8/viasor1ZR6W58t5WyYWUaeqOVT7RGeEY48i8VuHdze2tFydn7yR/bHwudewLHI+a1kLFdyHls6TbxWQl9Am95/QcVHkOl1OSdhlkNC4Y8WdfYEOy/o77baysU7NPTPiM9/HrBJHdI1VURApfH1JeYcQeeUn7VZ+oMD4ysOdylRrR0ABlFpINZDD9a/yj3fl0MfMm35/Jm3AVXlxQp9esrncJ1ScIDsTKsas537rqYin9CRYCMsSCt4VszEnqmNGzpwY9lXivdYrGqkrZ3t5n030SBq7XM2lG8mbk07hJv/fPW1Ml+ZzG3I3aTUBsdQBxDGPbK3Wg+E+l0B9NI8GS/4L8hveWkjZPqQyioQ997xJ0gCa43AZx7Nk9kFAMSrxGRawB/uR7Nsnb36FiNg70UbJdbqkdUAK9EzoazkoXQRM8l3UzzUX/dTHeYGNfbNadc+EtRWdLV9NSem+36LjIVd3apWajvaM0O+6KMn+8RyY8BHlFx9knMS8CRVN/CMqeBzYg7tmPPo8MJiE7wKdABEWONSs75Z5UeQH5H9n1m9W1ZLaM6kNb6zMpEbDWR7wMwWQD0gDTAX+JPbZwS9R5DHMZJ3Th2tmReihvQ==
  template:
    metadata:
      name: argocd-creds
      namespace: homepage
    type: Opaque
