{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tunnel-token",
    "namespace": "cloudflare-tunnel"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tunnel-token",
        "namespace": "cloudflare-tunnel"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "token": "AgAC2IWJCevU1C4YPZurELDnKb7ciSQ/Xbv/J1soUVkmy1ZPDg1zzYlxRW/qkkboTQM0YutQT6t65WXAJIPPvN2F63Fr5hhgGUkARMG/slYIiDqHQnRbhnae9rxJ/8qJWr9jo9sXXCzQ8j/VasNPiXra85MgxhuG2ssHH4xJinjw/glP5bi6FTg3LF0RB5/lbkZYf4xZEDAaovQtQ6NNWs1VElJ0r3J+Bz5FmVkZRSFNxfwxtxwrFku1bD0Q88YLuqRK5BcVmGliqUqrv9d3v8KOEU8HFMQpeRlrELypdWVW1zbE0HLf7kkWp241Owm5GfHSLh2DozLlcfL8ywgs6f6l2NqGzPgtnrHZbIEyg65HCHhgZRIIWDYGK34BzpJttiUarFL2xtFfwkV65L+PMpOn1YIS2gqBT7cQy2yvtVhyXgSe8LnG8DpH6Lggn6a6UZn9MsGndg1qk3tPu7x2FBUT3QArUiLH4oE/N26dD+xkUuj33xNi5tLJoLT1sdRIjyIc/GyK+HYmyWU2ByMkeOKAIULQgPF4pnWrE3HEvzeO1MIyj2ut9NJxpA/5I8gZfvUYNva05732UO2R5T6/Ap3lHRcQpxh1lTye/g98U5Ub+it9Yag6S/2CJLM2wo3U/+P9IZSgeyow01mNcAsK4CInt/YeDA7KzFx94kIrUq6OkfcRpPEHz7USlkkMihJDPR4Ns1sBdk+07z9TdWKBVaBYBw4vlSVmKc9sojHXNANDQ4vVj6lT5ihx83oNWdPoY7IlfE5Yr+KXk++y1aE96VSTh2o077SU3ruX/lqDp/NQhKGUXsZ/Hq7JIoWqJJcKyr4f4ARDTWkfOsR6dHE3mBhaFj+PQffAPsad61F+aVMJTsGhrxr6gPHp0ACH5dUDkrA4ER3z7j2kf4rx//bxhYsc4plOTvaHrp2/m24ZppV95IDXTvZubqyt"
    }
  }
}
