apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-nfs-pv
  labels:
    app: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.70
    path: /srv/nfs/uptime-kuma
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: uptime-kuma
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-init-script
  namespace: uptime-kuma
data:
  init-status-page.sh: |
    #!/bin/sh
    # Auto-create default status page if it doesn't exist
    
    DB_PATH="/app/data/kuma.db"
    SLUG="default"
    TITLE="Homelab Status"
    
    # Wait for database to be ready
    echo "Waiting for Uptime Kuma database..."
    until [ -f "$DB_PATH" ]; do
      sleep 2
    done
    
    # Check if status page exists
    STATUS_PAGE_COUNT=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM status_page WHERE slug='$SLUG';" 2>/dev/null || echo "0")
    
    if [ "$STATUS_PAGE_COUNT" = "0" ]; then
      echo "Status page '$SLUG' not found. Creating..."
      
      # Create status page
      sqlite3 "$DB_PATH" <<EOF
    INSERT INTO status_page (slug, title, description, icon, theme, published, show_tags, custom_css, show_powered_by)
    VALUES ('$SLUG', '$TITLE', 'Automated homelab monitoring', '/icon.svg', 'auto', 1, 0, '', 1);
    EOF
      
      # Get the status page ID
      STATUS_PAGE_ID=$(sqlite3 "$DB_PATH" "SELECT id FROM status_page WHERE slug='$SLUG';")
      
      # Add all monitors to the status page
      MONITOR_IDS=$(sqlite3 "$DB_PATH" "SELECT id FROM monitor;")
      
      for MONITOR_ID in $MONITOR_IDS; do
        echo "Adding monitor $MONITOR_ID to status page..."
        sqlite3 "$DB_PATH" "INSERT OR IGNORE INTO status_page_cname (status_page_id, monitor_id) VALUES ($STATUS_PAGE_ID, $MONITOR_ID);"
      done
      
      echo "Status page created successfully!"
    else
      echo "Status page '$SLUG' already exists. Skipping creation."
    fi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      initContainers:
      - name: wait-for-nfs
        image: busybox:latest
        command: ['sh', '-c', 'until [ -d /app/data ] && [ -w /app/data ]; do echo "Waiting for NFS mount..."; sleep 5; done; echo "NFS mount ready!"']
        volumeMounts:
        - name: data
          mountPath: /app/data
      - name: init-status-page
        image: louislam/uptime-kuma:latest
        command: ['sh', '/scripts/init-status-page.sh']
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: init-script
          mountPath: /scripts
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:latest
        ports:
        - containerPort: 3001
          name: http
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc
      - name: init-script
        configMap:
          name: uptime-kuma-init-script
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  type: LoadBalancer
  selector:
    app: uptime-kuma
  ports:
  - port: 3001
    targetPort: 3001
    name: http
