apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 5GB
            additionalScrapeConfigs:
              - job_name: 'cloudflare-lusostreams'
                scrape_interval: 60s
                scrape_timeout: 30s
                scheme: https
                basic_auth:
                  username: 'prometheus'
                  password: 'cfProm3th3us!Luso'
                static_configs:
                  - targets: ['cloudflare-prometheus-exporter.lusostreams.workers.dev']
                    labels:
                      account: 'lusostreams'
              - job_name: 'cloudflare-mdias'
                scrape_interval: 60s
                scrape_timeout: 30s
                scheme: https
                basic_auth:
                  username: 'prometheus'
                  password: 'cfProm3th3us!Mdias'
                static_configs:
                  - targets: ['cloudflare-prometheus-exporter.mdias-info.workers.dev']
                    labels:
                      account: 'mdias-info'
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: "10.10.10.201"
          persistence:
            enabled: true
            size: 1Gi
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
        prometheusOperator:
          admissionWebhooks:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /status/loadBalancer/ingress
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec

