apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 5GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: "10.10.10.201"
          persistence:
            enabled: true
            size: 1Gi
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
        prometheusOperator:
          admissionWebhooks:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /status/loadBalancer/ingress

